### ISSUE TITLE
Login using SSO Authentication

### ISSUE THREAD

**Issue by mariussl** [TileDB-Inc/TileDB-Cloud-Java#19]
We have a self deployed TileDBCloud cluster that uses Azure OpenIDConnect to login users. [This is supported by TileDB as documented here](https://docs.tiledb.com/enterprise/corporate-sso).

In the TileDB-Cloud-Java Client [TileDBLogin](https://github.com/TileDB-Inc/TileDB-Cloud-Java/blob/d11170eef09e43c8ff1e63766aec445abb3c3a3a/src/main/java/io/tiledb/cloud/TileDBLogin.java#L14C8-L14C8) I only see the option for the API Key and not an SSO OpenID Token.

Please provide a way that we can login a user using his/her OpenID SSO token.

**Comment by DimitrisStaratzis** [comment]
Hi @mariussl , 
Thank you for opening the issue. We expect to have this feature merged by Monday. An update to the latest spec is required. 

Best, 
Dimitris

**Comment by DimitrisStaratzis** [comment]
Hi @mariussl ,

The API clients only have support for authenticating via either direct TileDB username/password or API key. So a user logged in with SSO would want to create an API key and use that in io.tiledb.cloud.TileDBLogin in the Java client.
